mc/urls.py
from django.contrib import admin
from django.urls import path,re_path
from tournament.views import index,table,schedule,participant,account,test

urlpatterns = [
    re_path(r'^$',index.index),
    path('admin/', admin.site.urls),

    #首页
    path('index/',index.index),

    #赛事简介
    path('intro/',index.intro),

    #登录
    path('login/',account.login),
    path('visitor_login/',account.visitor_login),
    #退出登录
    path('logout/',account.logout),
    #获取验证码图片
    path('image/code/',account.code),

    
    #积分榜
    path('table/',table.table),
    path('participant_detail/',table.participant_detail),
    #选手详情页数据
    path('pdetail/bar_data/',table.pdetail_bar_data),
    path('pdetail/pie_data/',table.pdetail_pie_data),
    path('pdetail/radar_data/',table.pdetail_radar_data),
    #个人中心
    path('participant_information/',participant.participant_information),

    #选手
    path('participant_add/',participant.participant_add),
    path('participant_delete/',participant.participant_delete),

    #赛程
    path('schedule/',schedule.schedule),
    path('game_add/',schedule.game_add),

    #测试
    path('test/',test.doit),
    path('tmp/',test.tmp),

    
]

tournament/views/account.py
from django.http import HttpResponse
from django.shortcuts import  redirect, render
from tournament.utils.md5 import md5
from tournament import models
from django import forms
from tournament.utils.verificationcode import verification_code
from io import BytesIO

class LoginForm(forms.Form):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={"class":"form-control"}),
        required= True
        )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(attrs={"class":"form-control"},render_value=True),
        required= True)
    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput(attrs={"class":"form-control"}),
        required= True)

    def clean_password(self):
        cleaned_password = md5(self.cleaned_data.get("password"))
        return cleaned_password

def login(request):
    if request.method =="GET":
        form = LoginForm()
        return render(request,"login.html",{"form":form}) 
    form = LoginForm(data=request.POST)
    if form.is_valid():
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code','')
        if code != user_input_code.upper():
            form.add_error('code',"验证码错误")
            return render(request,"login.html",{"form":form})
        #print(form.cleaned_data)
        #print(form.cleaned_data.get('username'),form.cleaned_data.get('password'))
        obj = models.Participant.objects.filter(name=form.cleaned_data.get('username'),password=form.cleaned_data.get('password')).first()
        if  not obj:
            form.add_error("password","用户名或密码错误")
            return render(request,"login.html",{"form":form})
        request.session["info"] = {"id":obj.id,"username":obj.name}
        request.session.set_expiry(60*60*24*7)#7天免登录
        return redirect("/index")
    return render(request,"login.html",{"form":form})

def visitor_login(request):
    request.session["info"] = {"id":'游客',"username":'游客'}
    request.session.set_expiry(60*60*24*7)#7天免登录
    return redirect('/table/?event=1')

def logout(request):
    request.session.clear()
    return redirect("/index/")

def code(request):
    #返回验证码
    img,code_str = verification_code()
    #print("*******************",code_str)
    request.session['image_code'] = code_str
    request.session.set_expiry(60) #设置60秒有效时间
    stream = BytesIO()
    img.save(stream, 'png')

    return HttpResponse(stream.getvalue())

tournament/views/index.py
from django.shortcuts import render
from tournament import models

def index(request):
    njcup_top_3 = models.NewJourneyCup.objects.all().order_by('current_rank')[0:3]
    #fakecup_top_3 = models.FakeCup.objects.all().order_by('current_rank')[0:3]
    param_dict = {
        "njcup_top_3":njcup_top_3,
        #"fakecup_top_3":fakecup_top_3,
    }
    return render(request,'index.html',param_dict)

def intro(request):
    return render(request,'intro.html')

tournament/views/participant.py
from django.shortcuts import redirect, render
from tournament.utils.bootstrap_modelform import BootstrapModelForm
from tournament import models

class ParticipantModelForm(BootstrapModelForm):
    class Meta:
        model = models.Participant
        fields = ["name",'qq','gender','type_of_team','highest_rank']

def participant_add(request):
    if request.method == "GET":
        form = ParticipantModelForm()
        return render(request,"participant_add.html",{"form":form})
    form = ParticipantModelForm(data=request.POST)
    if form.is_valid():
        form.save()
    
    #计算更新所有选手排名
    # players = models.Participant.objects.all().order_by('-points')
    # i = 1
    # for p in players:
    #     models.Participant.objects.filter(id=p.id).update(current_rank=i)
    #     i = i + 1

    return redirect("/table")

def participant_delete(request):
    pid = request.GET.get('pid')
    models.Participant.objects.filter(id=pid).delete()

    #计算更新所有选手排名
    players = models.Participant.objects.all().order_by('-points')
    i = 1
    for p in players:
        models.Participant.objects.filter(id=p.id).update(current_rank=i)
        i = i + 1

    return redirect("/table")

def participant_information(request):

    return render(request,"participant_information.html")

tournament/views/schedule.py
from django.shortcuts import redirect, render
from tournament import models
from tournament.utils.bootstrap_modelform import BootstrapModelForm
from tournament.utils.pagination import Pagination
from tournament.views.test import update_fakecup_table,update_njcup_table

def schedule(request):
    query_set = models.Game.objects.all()

    page_obj = Pagination(request=request,queryset=query_set,page_size=8,step=2)
    page_queryset = page_obj.page_queryset
    page_string = page_obj.html()

    param_dict = {
        "query_set":page_queryset,
        "page_string":page_string
    }
    return render(request,"schedule.html",param_dict)

class GameModelForm(BootstrapModelForm):
    class Meta:
        model = models.Game
        fields = "__all__"


def game_add(request):
    if request.method == "GET":
        form = GameModelForm()
        param_dict = {
            "form":form,
        }
        return render(request,"game_add.html",param_dict)
    form = GameModelForm(data=request.POST)
    if form.is_valid():  

        if form.cleaned_data.get('home').name == request.session['info'].get('username') or\
            form.cleaned_data.get('away').name == request.session['info'].get('username'):
                form.save()      
        else:
            print("只能登记自己参加的比赛！")
        if form.cleaned_data.get('home').name == form.cleaned_data.get('away').name:
            print("不能自己踢自己！")

        if form.cleaned_data.get('event') == 1:     #更新新旅程杯积分表
            update_njcup_table()
        if form.cleaned_data.get('event') == 2:     #更新不存在的杯积分表
            update_fakecup_table()
            print("updated")
    
    return redirect('/table/?event='+ str(form.cleaned_data.get('event')))

tournament/views/table.py
from pyexpat import model
from unittest import result
from django.db.models import F, Q,Avg,Max,Sum
from django.http import JsonResponse
from django.shortcuts import render
from tournament import models


def table(request):
    if request.GET.get("event") == '1':  
        players = models.NewJourneyCup.objects.all().order_by('-points')

        club_players = models.NewJourneyCup.objects.all().filter(participant__type_of_team=1).order_by('-points')
        i = 1
        club_rank = []
        for p in club_players:
            club_rank.append([i,p])
            i = i + 1
        
        legend_players = models.NewJourneyCup.objects.all().filter(participant__type_of_team=2).order_by('-points')
        legend_rank = []
        i = 1
        for p in legend_players:
            legend_rank.append([i,p])
            i = i + 1
        
        param_dict = {
        "players":players,
        'club_players':club_rank,
        'legend_players':legend_rank
        }
        return render(request,'table.html',param_dict)
    if request.GET.get("event") == '2':  
        players = models.FakeCup.objects.all().order_by('-points')
        param_dict = {
        "players":players,
        }
        return render(request,'table.html',param_dict)
    
def get_participant_stat():

    #计算所有选手的平均进失球数，aggregate(Avg()) 返回字典类型 {'goals__avg': 30.3158}
    avg_goal = models.NewJourneyCup.objects.aggregate(Avg('goals'))
    avg_goal_conceded = models.NewJourneyCup.objects.aggregate(Avg('goals_conceded'))
    max_game_count = models.NewJourneyCup.objects.aggregate(Max('games'))
    result = {
        'avg_goal':avg_goal['goals__avg'],
        'avg_goal_conceded':avg_goal_conceded['goals_conceded__avg'],
        'max_game_count':max_game_count['games__max']
        }

    return result
    

def participant_detail(request):

    #从URL中获取当前查看的选手的id
    pid = request.GET.get('pid')
    #根据选手id从数据库中筛选选手参加的比赛
    games = models.Game.objects.filter(Q(home_id=pid)|Q(away_id=pid))

    #主场场数
    home_games = games.filter(home_id=pid)
    home_game_count = len(home_games)

    #客场场数
    away_games = games.filter(away_id=pid)
    away_game_count = len(away_games)

    #主场
    home_wins = home_games.filter(home_goal__gt=F('away_goal'))     
    home_win_count = len(home_wins)
    home_win_rate = '{:.0%}'.format(home_win_count / home_game_count)
    home_goal_count = home_games.aggregate(Sum('home_goal'))['home_goal__sum']
    home_goal_conceded_count = home_games.aggregate(Sum('away_goal'))['away_goal__sum']
    home_clean_sheet_count = len(home_games.filter(away_goal=0))
    home_big_win_count = len(home_games.filter(home_goal__gte=F('away_goal')+3))
    home_slaughter_count = len(home_games.filter(home_goal__gte=F('away_goal')+5))
    
    #客场
    away_wins = away_games.filter(away_goal__gt=F('home_goal'))
    away_win_count = len(away_wins)
    away_win_rate = '{:.0%}'.format(away_win_count / away_game_count)
    away_goal_count = away_games.aggregate(Sum('away_goal'))['away_goal__sum']
    away_goal_conceded = away_games.aggregate(Sum('home_goal'))['home_goal__sum']
    away_clean_sheet_count = len(away_games.filter(home_goal=0))
    away_big_win_count = len(away_games.filter(away_goal__gte=F('home_goal')+3))
    away_slaughter_count = len(away_games.filter(away_goal__gte=F('home_goal')+5))


    details = [
        ['胜率',home_win_rate,away_win_rate],
        ['进球数',home_goal_count,away_goal_count],
        ['失球数',home_goal_conceded_count,away_goal_conceded],
        ['零封场数',home_clean_sheet_count,away_clean_sheet_count],
        ['净胜3+球场数',home_big_win_count,away_big_win_count],
        ['净胜5+球场数',home_slaughter_count,away_slaughter_count]
    ]
   
    param_dict = {
        "games":games,
        "home_games":home_games,
        'details':details,
    }

    return render(request,'participant_detail.html',param_dict)

def pdetail_bar_data(request):
    pid = request.GET.get('pid')

    #根据选手id从数据库中筛选选手参加的比赛
    games = models.Game.objects.filter(Q(home_id=pid)|Q(away_id=pid))

    #比赛场数
    game_count =len(games)
    #主场场数
    home_games = games.filter(home_id=pid)
    home_game_count = len(home_games)
    #客场场数
    away_games = games.filter(away_id=pid)
    away_game_count = len(away_games)
    #主场胜、平、负
    home_wins = home_games.filter(home_goal__gt=F('away_goal'))     
    home_draws = home_games.filter(home_goal=F('away_goal'))
    home_loses = home_games.filter(home_goal__lt=F('away_goal'))
    home_win_count, home_draw_count, home_lose_count = len(home_wins),\
        len(home_draws), len(home_loses)
    home_win_rate, home_draw_rate, home_lose_rate =\
        home_win_count / home_game_count,\
        home_draw_count / home_game_count,\
        home_lose_count / home_game_count
    
    #客场胜、平、负
    away_wins = away_games.filter(away_goal__gt=F('home_goal'))
    away_draws = away_games.filter(away_goal=F('home_goal'))
    away_loses = away_games.filter(away_goal__lt=F('home_goal'))
    away_win_count, away_draw_count, away_lose_count = len(away_wins),\
        len(away_draws), len(away_loses)
    away_win_rate, away_draw_rate, away_lose_rate =\
        away_win_count / away_game_count,\
        away_draw_count / away_game_count,\
        away_lose_count / away_game_count

    db_data_list = [
    {
      'name': '胜',
      'type': 'bar',
      'stack': 'total',
      'label': {
        'show': 'true'
      },
      'emphasis': {
        'focus': 'series'
      },
      'data': [home_win_count+away_win_count,]
    },
    {
      'name': '平',
      'type': 'bar',
      'stack': 'total',
      'label': {
        'show':'true'
      },
      'emphasis': {
        'focus': 'series'
      },
      'data': [home_draw_count+away_draw_count,]
    },
    {
      'name': '负',
      'type': 'bar',
      'stack': 'total',
      'label': {
        'show':'true'
      },
      'emphasis': {
        'focus': 'series'
      },
      'data': [home_lose_count+away_lose_count,]
    },
    

  ]
    result = {
        "status":True,
        "data":db_data_list
    }
    return JsonResponse(result)


def pdetail_pie_data(request):
    pid = request.GET.get('pid')

    #根据选手id从数据库中筛选选手参加的比赛
    games = models.Game.objects.filter(Q(home_id=pid)|Q(away_id=pid))

    #比赛场数
    game_count =len(games)
    #主场场数
    home_games = games.filter(home_id=pid)
    home_game_count = len(home_games)
    #客场场数
    away_games = games.filter(away_id=pid)
    away_game_count = len(away_games)
    #主场胜、平、负
    home_wins = home_games.filter(home_goal__gt=F('away_goal'))     
    home_draws = home_games.filter(home_goal=F('away_goal'))
    home_loses = home_games.filter(home_goal__lt=F('away_goal'))
    home_win_count, home_draw_count, home_lose_count = len(home_wins),\
        len(home_draws), len(home_loses)
    home_win_rate, home_draw_rate, home_lose_rate =\
        home_win_count / home_game_count,\
        home_draw_count / home_game_count,\
        home_lose_count / home_game_count
    
    #客场胜、平、负
    away_wins = away_games.filter(away_goal__gt=F('home_goal'))
    away_draws = away_games.filter(away_goal=F('home_goal'))
    away_loses = away_games.filter(away_goal__lt=F('home_goal'))
    away_win_count, away_draw_count, away_lose_count = len(away_wins),\
        len(away_draws), len(away_loses)
    away_win_rate, away_draw_rate, away_lose_rate =\
        away_win_count / away_game_count,\
        away_draw_count / away_game_count,\
        away_lose_count / away_game_count

    db_data_list = [
        { "value": home_win_count + away_win_count, "name": '胜' },
        { "value": home_draw_count + away_draw_count, "name": '平' },
        { "value": home_lose_count + away_lose_count, "name": '负' },
    ]
    result = {
        "status":True,
        "data":db_data_list
    }
    return JsonResponse(result)

def pdetail_radar_data(request):
    pid = request.GET.get('pid')
    p = models.NewJourneyCup.objects.filter(participant=pid).first()
    name = models.Participant.objects.filter(id=pid).first().name
    #根据选手id从数据库中筛选选手参加的比赛
    games = models.Game.objects.filter(Q(home_id=pid)|Q(away_id=pid))
    begin_date = games.order_by('game_date').first().game_date
    finish_date = games.order_by('-game_date').first().game_date

    #比赛场数
    game_count =len(games)
    #主场场数
    home_games = games.filter(home_id=pid)
    home_game_count = len(home_games)
    #客场场数
    away_games = games.filter(away_id=pid)
    away_game_count = len(away_games)
    #主场胜、平、负
    home_wins = home_games.filter(home_goal__gt=F('away_goal'))     
    home_draws = home_games.filter(home_goal=F('away_goal'))
    home_loses = home_games.filter(home_goal__lt=F('away_goal'))
    home_win_count, home_draw_count, home_lose_count = len(home_wins),\
        len(home_draws), len(home_loses)
    home_win_rate, home_draw_rate, home_lose_rate =\
        home_win_count / home_game_count,\
        home_draw_count / home_game_count,\
        home_lose_count / home_game_count
    
    #客场胜、平、负
    away_wins = away_games.filter(away_goal__gt=F('home_goal'))
    away_draws = away_games.filter(away_goal=F('home_goal'))
    away_loses = away_games.filter(away_goal__lt=F('home_goal'))
    away_win_count, away_draw_count, away_lose_count = len(away_wins),\
        len(away_draws), len(away_loses)
    away_win_rate, away_draw_rate, away_lose_rate =\
        away_win_count / away_game_count,\
        away_draw_count / away_game_count,\
        away_lose_count / away_game_count
    
    data_list = [{
        'name': 'hahahahha',
                'type': 'radar',
                'data': [
                    {
                    'value': [
                            (home_win_count + away_win_count) / game_count * 100,
                            p.goals / p.games * 30,
                            100 - p.goals_conceded / p.games * 10,
                            100 - abs((home_win_count/home_game_count-away_win_count/away_game_count)) * 100,

tournament/templates/game_add.html
{% extends "layout.html" %}

{%block content%}
<div>
    <div class="container">
      <!--<div style="margin-bottom: 10px;">
            <a class="btn btn-success" href="/admin/add/">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
              按钮
            </a>
        </div>
      -->
      
      <div class="panel panel-default">
            <div class="panel-heading">
              <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
              添加比赛
            </div>
            <div class="panel-body">
              <div class="bs-example" data-example-id="simple-table">
                <form method="post">
                  {% csrf_token %}
                  {% for field in form%}
                  {{field.label}}
                  {{field}}
                  {% endfor %}
                  <div>
                    <button type="submit" class="btn btn-primary">提交</button>
                  </div>
                </form>
              </div>
            </div>
      </div>
    </div>
    
</div>


{%endblock%}

tournament/templates/index.html
{% extends "layout.html" %}

{% block content %}

    <div class="container">


    <div class="jumbotron">
      <h1>新旅程杯</h1>
      <table class="table table-boarderd table-hover">
                  
        <thead>
          <tr>
            <th>排名</th>
            <th>赛</th>
            <th>胜</th>
            <th>平</th>
            <th>负</th>
            <th>进/失</th>
            <th>积分</th>
          </tr>
        </thead>
        <tbody>
          {% for item in njcup_top_3%}
          <tr>
            <td><a href="/participant_detail/?pid={{item.id}}">{{item.current_rank}} {{item.participant.name}}</a></td>
            <td>{{item.games}}</td>
            <td>{{item.wins}}</td>
            <td>{{item.draws}}</td>
            <td>{{item.losts}}</td>
            <td>{{item.goals}}/{{item.goals_conceded}}</td>
            <td>{{item.points}}</td>
          </tr>
          {%endfor%}
        </tbody>
      </table> 
      <p><a class="btn btn-primary btn-lg" href="/table/?event=1" role="button">查看完整积分榜</a></p>

    </div>

    <div class="row">
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail" style="height: 400px;">
          <img data-src="holder.js/100%x200" alt="100%x200" style="height: 200px; width: 60%; display: block ;margin-top: 20px;" src="/static/img/ol3_logo_1.png" data-holder-rendered="true">
          <div class="caption">
            <h3>比赛平台 FIFA Online3</h3>
            <p>《EA SPORTS™ FIFA Online 3》是一款以足球为主题的大型多人在线游戏，属于模拟体育运动游戏。国服由腾讯游戏代理,已于2021年6月7日0点停止运营，并更新至《FIFA Online4》。</p>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail" style="height: 400px;">
          <img data-src="holder.js/100%x200" alt="100%x200" class="img-rounded" style="height: 200px; width: 60%; display: block;margin-top: 20px;" src="/static/img/group_logo.jpg" data-holder-rendered="true">
          <div class="caption">
            <h3>华东曼城战队</h3>
            <p>FIFA Online3曼城战队是华东大区最早建立的英格兰足球超级联赛曼城俱乐部球迷战队，见证了国内曼城球迷群体的发展壮大。战队成员除了在游戏内切磋技艺，还举行过2019英超亚洲杯上海赛区的的线下观赛等活动。</p>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail" style="height: 400px;">
          <img data-src="holder.js/100%x200" alt="100%x200" style="height: 200px; width: 70%; display: block;margin-top: 20px;" src="/static/img/njcup.png" data-holder-rendered="true">
          <div class="caption">
            <h3>新旅程杯</h3>
            <p>新旅程杯是战队内新一届比赛，根据参赛选手在游戏中使用的球员类型分为传奇组和队套组。两个小组分别进行组内双循环比赛决出名次，传奇组和队套组的第一名将角逐本届比赛的总冠军。
            <br><a href="https://docs.qq.com/document/DSElvSk9Xdktyb0hy?u=591de289e1104352b17f478d1aa2bf2f">详细赛制</a>
            </p> 
          </div>
        </div>
      </div>
    </div>

    </div>

    <!--
      <div class="container">
      <div class="jumbotron">
        <h1>不存在的杯</h1>
        <table class="table table-boarderd table-hover">
                    
          <thead>
            <tr>
              <th>排名</th>
              <th>赛</th>
              <th>胜</th>
              <th>平</th>
              <th>负</th>
              <th>进/失</th>
              <th>积分</th>
            </tr>
          </thead>
          <tbody>
            {% for item in fakecup_top_3%}
            <tr>
              <td><a href="/participant_detail/?pid={{item.participant_id}}">{{item.current_rank}} {{item.participant.name}}</a></td>
              <td>{{item.games}}</td>
              <td>{{item.wins}}</td>
              <td>{{item.draws}}</td>
              <td>{{item.losts}}</td>
              <td>{{item.goals}}/{{item.goals_conceded}}</td>
              <td>{{item.points}}</td>
            </tr>
            {%endfor%}
          </tbody>
        </table> 
        <p><a class="btn btn-primary btn-lg" href="/table/?event=2" role="button">查看完整积分榜</a></p>
      </div>
    -->
    
      </div>

{% endblock %}

{%block js%}
    <script src="\static\js\echarts.min.js"></script>
    <script type="text/javascript">
            $(function(){
                initHeat();
            })

            function initHeat(){
                var myChart = echarts.init(document.getElementById('heat'));
                function getVirtulData(year) {
                    year = year || '2017';
                    var date = +echarts.number.parseDate(year + '-09-01');
                    var end = +echarts.number.parseDate(+year + 1 + '-11-01');
                    var dayTime = 3600 * 24 * 1000;
                    var data = [];
                    for (var time = date; time < end; time += dayTime) {
                        data.push([
                        echarts.format.formatTime('yyyy-MM-dd', time),
                        Math.floor(Math.random() * 10000)
                        ]);
                    }
                    return data;
                    }
                    option = {
                    title: {
                        top: 30,
                        left: 'center',
                        text: '比赛日期热力图'
                    },
                    tooltip: {},
                    visualMap: {
                        min: 0,
                        max: 10000,
                        type: 'piecewise',
                        orient: 'horizontal',
                        left: 'center',
                        top: 65
                    },
                    calendar: {
                        top: 120,
                        left: 30,
                        right: 30,
                        cellSize: ['auto', 13],
                        range: '2016',
                        itemStyle: {
                        borderWidth: 0.5
                        },
                        yearLabel: { show: false }
                    },
                    series: {
                        type: 'heatmap',
                        coordinateSystem: 'calendar',
                        data: getVirtulData('2016')
                    }
                    };
                    myChart.setOption(option);
            }
    
    </script>
{%endblock%}

tournament/templates/login.html
{%extends 'layout.html'%}

{%block content%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
    <link rel="stylesheet"  href="/static/plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css">
</head>
{%block css%}

<style type="text/css">
    .account{
        width: 400px;
        background-color: aliceblue;
        border: 1px solid #dddddd;
        border-radius: 5px;
        box-shadow: 5px 5px 20px #aaa;
        margin-left: auto;
        margin-right: auto;
        margin-top: 150px;
        padding: 20px 40px;
    }
    .account h2{
        margin-top: 10px;
        text-align: center;
    }

</style>
{%endblock%}

<body>
        <div class="account">
            <h2>用户登录</h2>
            <form method="post" novalidate> 
                {% csrf_token %}
                <label>用户名</label>
                {{form.username}}
        
                <br>
        
                <label >密码</label>
                {{form.password}}
                <span style="color:red;" >{{form.password.errors.0}}</span>
                <br>
                
                <div class="form-group">
                    <label for="id_code">图片验证码</label>
                    <div class="row">
                        <div class="col-xs-7">
                            {{form.code}}
                            <span style="color:red;" >{{form.code.errors.0}}</span>
                        </div>
                        <div class="col-xs-5">
                            <img id="image_code" src="/image/code/">
                        </div>
                    </div>    
                </div>
                <button type="submit" class="btn btn-binary">登录</button>
                <a href="/visitor_login/" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    游客登录
                </a>
            </form>
            
        </div>
          
{%endblock%}  



</body>
</html>

tournament/templates/participant_add.html
{% extends "layout.html" %}

{%block content%}
<div>
    <div class="container">
      <!--<div style="margin-bottom: 10px;">
            <a class="btn btn-success" href="/admin/add/">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
              按钮
            </a>
        </div>
      -->
      
      <div class="panel panel-default">
            <div class="panel-heading">
              <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
              添加选手
            </div>
            <div class="panel-body">
              <div class="bs-example" data-example-id="simple-table">
                <form method="post">
                  {% csrf_token %}
                  {% for field in form%}
                  {{field.label}}
                  {{field}}
                  {% endfor %}
                  <div>
                    <button type="submit" class="btn btn-primary">提交</button>
                  </div>
                </form>
              </div>
            </div>
      </div>
    </div>
    
</div>


{%endblock%}

tournament/templates/participant_information.html
{% extends 'layout.html' %}

{% block content %}

<ul class="nav nav-pills nav-justified">
    <li role="presentation"><a href="#">我的比赛</a></li>
    <li role="presentation"><a href="#">比赛登记</a></li>
    <li role="presentation"><a href="#">消息</a></li>
</ul>


{% endblock %}